import {useEffect,useState} from 'react'
import {NavLink,Route,Routes} from 'react-router-dom'
import {Activity,BrainCircuit,Clock3,Info,Moon,Sun} from 'lucide-react'
import {Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts'
import {detect,getHistory} from './services/api'

const pct=n=>Math.round((n||0)*100)
function Shell({dark,setDark,children}){return <div className="min-h-screen"><header className="border-b border-white/10"><div className="mx-auto flex max-w-6xl items-center justify-between p-5"><NavLink to="/" className="flex items-center gap-2 font-semibold"><BrainCircuit className="text-accent"/> Verity AI</NavLink><nav className="flex items-center gap-5 text-sm"><NavLink to="/detect">Detect</NavLink><NavLink to="/history">History</NavLink><NavLink to="/about">About</NavLink><button aria-label="Toggle theme" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button></nav></div></header>{children}</div>}
function Home(){return <main className="mx-auto max-w-6xl px-6 py-24"><span className="pill">Evidence, not guesswork</span><h1 className="mt-7 max-w-4xl text-6xl font-semibold leading-tight">Catch confident fiction before it ships.</h1><p className="mt-6 max-w-2xl text-xl text-slate-400">Verity retrieves trusted context, measures semantic support, and explains when an LLM answer drifts away from the facts.</p><NavLink className="button mt-9 inline-flex" to="/detect">Analyze an answer →</NavLink><div className="mt-24 grid gap-4 md:grid-cols-3">{[['Retrieve','Top-K evidence from your FAISS knowledge base.'],['Compare','Normalized embeddings measure semantic grounding.'],['Explain','Useful scores and evidence—not a mystery label.']].map(x=><section className="card" key={x[0]}><h2>{x[0]}</h2><p>{x[1]}</p></section>)}</div></main>}
function Result({data}){const chart=data.retrieved_evidence?.map(x=>({name:'#'+x.rank,similarity:pct(x.similarity)}))||[];return <div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="card"><div className="flex justify-between"><span className="pill">{data.prediction}</span><strong className="text-4xl">{pct(data.confidence)}%</strong></div><h2 className="mt-8">Confidence</h2><div className="meter"><i style={{width:pct(data.confidence)+'%'}}/></div><p className="mt-5 text-slate-400">{data.reason}</p><div className="mt-6 h-52"><ResponsiveContainer><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" stroke="#273142"/><XAxis dataKey="name"/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="similarity" fill="#67e8c6" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></section><section className="space-y-3"><h2>Retrieved evidence</h2>{data.retrieved_evidence?.map(x=><article className="card" key={x.rank}><div className="mb-3 flex justify-between text-xs text-slate-400"><span>RANK {x.rank}</span><span>{pct(x.similarity)}% match</span></div><p>{x.document.text}</p></article>)}</section></div>}
function Detect(){const [form,setForm]=useState({question:'Who created Python?',answer:'Python was created by Guido van Rossum in 1991.',top_k:5}),[result,setResult]=useState(),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e){e.preventDefault();setBusy(true);setError('');try{setResult(await detect(form))}catch(err){setError(err.response?.data?.detail?.[0]?.msg||'The API could not be reached.')}finally{setBusy(false)}}return <main className="mx-auto max-w-6xl px-6 py-14"><h1 className="text-4xl font-semibold">Grounding analysis</h1><p className="mt-2 text-slate-400">Compare an answer with your indexed knowledge.</p><form className="card mt-8 space-y-5" onSubmit={submit}><label>Question<textarea value={form.question} onChange={e=>setForm({...form,question:e.target.value})}/></label><label>LLM answer<textarea rows="5" value={form.answer} onChange={e=>setForm({...form,answer:e.target.value})}/></label>{error&&<p className="text-red-400">{error}</p>}<button className="button" disabled={busy}>{busy?'Retrieving evidence…':'Run detection'}</button></form>{result&&<Result data={result}/>}</main>}
function History(){const [items,setItems]=useState([]);useEffect(()=>{getHistory().then(setItems).catch(()=>{})},[]);return <main className="mx-auto max-w-6xl px-6 py-14"><h1 className="text-4xl font-semibold">History</h1><div className="mt-8 space-y-3">{items.length?items.map(x=><article className="card flex items-center gap-4" key={x.id}><Clock3 className="text-accent"/><div className="grow"><strong>{x.question}</strong><p className="line-clamp-1 text-sm text-slate-400">{x.answer}</p></div><span className="pill">{x.prediction}</span></article>):<p className="text-slate-400">No analyses yet.</p>}</div></main>}
function About(){return <main className="mx-auto max-w-3xl px-6 py-20"><Info className="text-accent" size={40}/><h1 className="mt-5 text-4xl font-semibold">Transparent by design.</h1><p className="mt-5 text-lg text-slate-400">Verity is a portfolio-grade RAG evaluation system. It combines sentence-transformer embeddings, FAISS retrieval, evidence scoring, FastAPI, and an inspectable local history.</p></main>}
export default function App(){const [dark,setDark]=useState(localStorage.theme!=='light');useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.theme=dark?'dark':'light'},[dark]);return <Shell dark={dark} setDark={setDark}><Routes><Route path="/" element={<Home/>}/><Route path="/detect" element={<Detect/>}/><Route path="/history" element={<History/>}/><Route path="/about" element={<About/>}/></Routes></Shell>}
